# STUDENT INFO INITIAL LOOK

In [7]:
# Import libraries
import pandas as pd
import numpy as np

In [8]:
# Load the data
df = pd.read_csv('data/RTT_36_data.csv')
df

,ID,Start time,Completion time,Email,Name,Last modified time,What is your cohort number?,What month did your cohort start?,What year is it?,What is your age?,...,What streaming services do you subscribe to?,"Are you a dog person, cat person, both, or neither?",Does pineapple belong on pizza?,What is your favorite color?,What destination would you choose?,Favorite board / card game?,Favorite video game?,Favorite movie?,Favorite TV show?,What is your favorite sport to watch or play?
0,1,8/4/26 11:47:47,8/4/26 11:53:02,anonymous,NaN,NaN,2026-RTT-36,August,2026,36,...,Netflix;Youtube;,Neither,5.0,Green,Mountains,monopoly,NaN,avengers,Harry potter,badminton
1,2,8/4/26 11:48:01,8/4/26 11:53:11,anonymous,NaN,NaN,2026 RTT-36,August,2026,38,...,Netflix;Youtube;Hulu;,Both,1.0,Green,National Park,uno,Mario Kart,Friday,Blackish,Basketball
2,3,8/4/26 11:47:53,8/4/26 11:53:12,anonymous,NaN,NaN,36,August,2026,28,...,Netflix;Hulu;HBO;Paramount;,Both,5.0,Blue,Mountains,Uno,Pac Man,The Shack,Avatar the Last Airbender,Tennis
3,4,8/4/26 11:48:01,8/4/26 11:54:22,anonymous,NaN,NaN,2026-rtt-36,August,2026,37,...,Netflix;mobilvids;,Both,5.0,Green,Countryside,monopoly,Tempest Rising,Bicentennial man,super natural,"Gold, Play"
4,5,8/4/26 11:48:32,8/4/26 11:54:34,anonymous,NaN,NaN,2026-RTT-36,August,2026,27,...,Netflix;Youtube;,Dog,3.0,White,Beach,UNO,God of war,Kantara,Young Sheldon,Cricket
5,6,8/4/26 11:47:42,8/4/26 11:54:51,anonymous,NaN,NaN,2026 - RTT -36,August,2026,41,...,NaN,Neither,5.0,Yellow,Beach,NaN,NaN,NaN,NaN,Tennis
6,7,8/4/26 11:48:14,8/4/26 11:55:29,anonymous,NaN,NaN,36,August,2026,46,...,Hulu;HBO;,Both,5.0,Black,Beach,Monopoly,Skyrim elder scrolls,Living Out Loud,Sex and the city,basketball
7,8,8/4/26 11:48:06,8/4/26 11:55:42,anonymous,NaN,NaN,2026-RTT-36,August,2026,38,...,Netflix;,Neither,5.0,Green,Countryside,puzzle,no,no,no,soccer
8,9,8/4/26 11:48:08,8/4/26 11:55:59,anonymous,NaN,NaN,36,August,2026,31,...,Netflix;Hulu;HBO;Peacock;Disney;,Dog,3.0,Green,Mountains,What Do You Meme,Mario Kart,The Pianist,Schitts Creek,"Watch soccer, play volleyball"
9,10,8/4/26 11:47:49,8/4/26 11:56:16,anonymous,NaN,NaN,RTT-36,August,2026,23,...,Netflix;Paramount;Hulu;HBO;Prime ;,Dog,2.0,Brown,Big City,Monopoly,Call of Duty,Lion King,Spongebob,Basketball
10,11,8/4/26 11:48:47,8/4/26 11:56:51,anonymous,NaN,NaN,2026-RTT-36,August,2026,38,...,Netflix;HBO;Peacock;,Both,2.0,Purple,Beach,uno,mario,twilight,not sure,football
11,12,8/4/26 11:48:01,8/4/26 11:57:12,anonymous,NaN,NaN,2026-RT-36,August,2026,45,...,Netflix;Hulu;,Cat,1.0,Red,Beach,monopoly,Assassin Creed,Casablanca,Jack Richard,Athletics
12,13,8/4/26 11:47:51,8/4/26 11:58:21,anonymous,NaN,NaN,2026-RTT-36,August,2026,39,...,"Paramount;Peacock;HBO;Hulu;Netflix;Prime, Star...",Neither,1.0,Green,Beach,Taboo,Mortal Kombat,Last Samurai,Game of Thrones,Football
13,14,8/4/26 11:47:42,8/4/26 11:58:51,anonymous,NaN,NaN,2026-RTT-36,August,2026,32,...,Netflix;Hulu;,Neither,5.0,Black,Beach,Spades,UFC,You Got Served,Bernie Mac Show,Rugby
14,15,8/4/26 11:47:44,8/4/26 12:00:34,anonymous,NaN,NaN,2026-rtt-36,August,2026,39,...,Netflix;,Neither,5.0,Orange,Beach,Sequence,No,Indian/Bahubali,NaN,Badminton
15,16,8/4/26 11:47:46,8/4/26 12:00:39,anonymous,NaN,NaN,2026-rtt-36,August,2026,40,...,Netflix;Youtube;,Dog,NaN,Blue,Beach,UNO,Mortal Kombat,Matrix,Walking Dead,MMA
16,17,8/4/26 11:47:54,8/4/26 12:00:59,anonymous,NaN,NaN,36,August,2026,25,...,Netflix;Youtube;,Neither,1.0,Purple,Mountains,"chess, badminton",Pub G,The pursuit of happiness,none,"football, wrestling"
17,18,8/4/26 11:47:47,8/4/26 12:01:40,anonymous,NaN,NaN,2026-RTT-36,August,2026,37,...,Netflix;,Neither,5.0,Green,Mountains,UNO,NaN,Avatar,gilmore girls,soccer
18,19,8/4/26 11:48:16,8/4/26 12:01:51,anonymous,NaN,NaN,2026-RTT-36,August,2026,33,...,Peacock;Paramount;,Dog,1.0,Green,Big City,Ludo,God of War,White Chicks,Loki,Soccer
19,20,8/4/26 11:48:06,8/4/26 12:02:43,anonymous,NaN,NaN,2026-rrt-36,August,2026,50,...,Netflix;Hulu;Youtube;,Cat,5.0,Green,Beach,NaN,NaN,Titanic,I mostly watch YouTube.,Soccer
20,21,8/4/26 11:47:42,8/4/26 12:03:37,anonymous,NaN,NaN,2026-36,August,2026,42,...,Netflix;Hulu;Paramount;HBO;Disney;,Neither,4.0,Black,National Park,UNO,Mario Brothers,Malcom X,Martin,NaN
21,22,8/4/26 11:47:45,8/4/26 12:03:49,anonymous,NaN,NaN,2026-rtt-36,August,2026,45,...,"Netflix;Hulu;foxOne, roku, prime, ;",Cat,4.0,Black,Big City,chess,none,not sure,NaN,soccer and tennis
22,23,8/4/26 11:47:44,8/4/26 12:04:15,anonymous,NaN,NaN,2026-rtt-36,August,2026,38,...,Netflix;Hulu;Peacock;,Neither,1.0,Green,Beach,Uno and Solitaire,Candy Crush Saga,"The Notebook , Inception , and White Chicks",Scandal and This is us,Soccer
23,24,8/4/26 11:47:44,8/4/26 12:05:03,anonymous,NaN,NaN,2026-RTT-36,August,2026,38,...,Netflix;Hulu;Youtube;,Dog,1.0,Blue,Beach,monopoly,2k,black panther,billions,boxing
24,25,8/4/26 11:47:52,8/4/26 12:17:23,anonymous,NaN,NaN,2026-RT-36,August,2026,44,...,"None, I'm not subscribed to any of those strea...",Both,2.0,Black,Big City,"Spades, UNO",Madden Football and Soul Caliber,"Stomp The yard, You Got Served, Saw","America's Best Dance Crew, So You Think You Ca...",Football and Basketball
25,26,8/4/26 11:48:02,8/4/26 12:38:12,anonymous,NaN,NaN,2026-RTT-36,August,2026,63,...,Amazon Prime;,Both,5.0,Orange,Mountains,Solitaire,NaN,Fifth-Element,Reacher,Snowboarding
26,27,8/4/26 11:47:50,8/4/26 12:50:19,anonymous,NaN,NaN,2026-rtt-36,August,2026,32,...,Netflix;Prime;,Neither,3.0,Blue,National Park,Non,Non,Empire Waist,Arrested Development,Soccer
27,28,8/4/26 12:58:33,8/4/26 13:01:35,anonymous,NaN,NaN,RTT-36,August,2026,19,...,None;,Cat,4.0,Blue,Mountains,Monopoly,COD mobile,Scooby Doo,Henry Danger,Running
28,29,8/4/26 13:07:43,8/4/26 13:14:10,anonymous,NaN,NaN,2026-RTT-36,August,2026,34,...,NaN,Dog,5.0,Green,Beach,Sorry,Bomberman Hero,A Walk to Remember,NaN,"Basketball, Flag Football"

In [9]:
# Data initial look
rows, cols = df.shape
print(f'Rows: {rows}')
print(f'Cols: {cols}')

Rows: 29
Cols: 55

In [10]:
df.head()

,ID,Start time,Completion time,Email,Name,Last modified time,What is your cohort number?,What month did your cohort start?,What year is it?,What is your age?,...,What streaming services do you subscribe to?,"Are you a dog person, cat person, both, or neither?",Does pineapple belong on pizza?,What is your favorite color?,What destination would you choose?,Favorite board / card game?,Favorite video game?,Favorite movie?,Favorite TV show?,What is your favorite sport to watch or play?
0,1,8/4/26 11:47:47,8/4/26 11:53:02,anonymous,NaN,NaN,2026-RTT-36,August,2026,36,...,Netflix;Youtube;,Neither,5.0,Green,Mountains,monopoly,NaN,avengers,Harry potter,badminton
1,2,8/4/26 11:48:01,8/4/26 11:53:11,anonymous,NaN,NaN,2026 RTT-36,August,2026,38,...,Netflix;Youtube;Hulu;,Both,1.0,Green,National Park,uno,Mario Kart,Friday,Blackish,Basketball
2,3,8/4/26 11:47:53,8/4/26 11:53:12,anonymous,NaN,NaN,36,August,2026,28,...,Netflix;Hulu;HBO;Paramount;,Both,5.0,Blue,Mountains,Uno,Pac Man,The Shack,Avatar the Last Airbender,Tennis
3,4,8/4/26 11:48:01,8/4/26 11:54:22,anonymous,NaN,NaN,2026-rtt-36,August,2026,37,...,Netflix;mobilvids;,Both,5.0,Green,Countryside,monopoly,Tempest Rising,Bicentennial man,super natural,"Gold, Play"
4,5,8/4/26 11:48:32,8/4/26 11:54:34,anonymous,NaN,NaN,2026-RTT-36,August,2026,27,...,Netflix;Youtube;,Dog,3.0,White,Beach,UNO,God of war,Kantara,Young Sheldon,Cricket

In [11]:
df.tail()

,ID,Start time,Completion time,Email,Name,Last modified time,What is your cohort number?,What month did your cohort start?,What year is it?,What is your age?,...,What streaming services do you subscribe to?,"Are you a dog person, cat person, both, or neither?",Does pineapple belong on pizza?,What is your favorite color?,What destination would you choose?,Favorite board / card game?,Favorite video game?,Favorite movie?,Favorite TV show?,What is your favorite sport to watch or play?
24,25,8/4/26 11:47:52,8/4/26 12:17:23,anonymous,NaN,NaN,2026-RT-36,August,2026,44,...,"None, I'm not subscribed to any of those strea...",Both,2.0,Black,Big City,"Spades, UNO",Madden Football and Soul Caliber,"Stomp The yard, You Got Served, Saw","America's Best Dance Crew, So You Think You Ca...",Football and Basketball
25,26,8/4/26 11:48:02,8/4/26 12:38:12,anonymous,NaN,NaN,2026-RTT-36,August,2026,63,...,Amazon Prime;,Both,5.0,Orange,Mountains,Solitaire,NaN,Fifth-Element,Reacher,Snowboarding
26,27,8/4/26 11:47:50,8/4/26 12:50:19,anonymous,NaN,NaN,2026-rtt-36,August,2026,32,...,Netflix;Prime;,Neither,3.0,Blue,National Park,Non,Non,Empire Waist,Arrested Development,Soccer
27,28,8/4/26 12:58:33,8/4/26 13:01:35,anonymous,NaN,NaN,RTT-36,August,2026,19,...,None;,Cat,4.0,Blue,Mountains,Monopoly,COD mobile,Scooby Doo,Henry Danger,Running
28,29,8/4/26 13:07:43,8/4/26 13:14:10,anonymous,NaN,NaN,2026-RTT-36,August,2026,34,...,NaN,Dog,5.0,Green,Beach,Sorry,Bomberman Hero,A Walk to Remember,NaN,"Basketball, Flag Football"

In [12]:
df.describe()

,ID,Name,Last modified time,What year is it?,What is your age?,How many siblings do you have?,How comfortable are you learning new technology?,Does pineapple belong on pizza?
count,29.000000,0.0,0.0,29.0,29.000000,29.000000,29.000000,28.000000
mean,15.000000,NaN,NaN,2026.0,37.172414,2.655172,4.655172,3.357143
std,8.514693,NaN,NaN,0.0,8.705782,2.635958,0.613879,1.704336
min,1.000000,NaN,NaN,2026.0,19.000000,0.000000,3.000000,1.000000
25%,8.000000,NaN,NaN,2026.0,32.000000,1.000000,4.000000,1.750000
50%,15.000000,NaN,NaN,2026.0,38.000000,2.000000,5.000000,4.000000
75%,22.000000,NaN,NaN,2026.0,41.000000,4.000000,5.000000,5.000000
max,29.000000,NaN,NaN,2026.0,63.000000,12.000000,5.000000,5.000000

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 55 columns):
 #   Column                                                                          Non-Null Count  Dtype
---  ------                                                                          --------------  -----
 0   ID                                                                              29 non-null     int64
 1   Start time                                                                      29 non-null     str
 2   Completion time                                                                 29 non-null     str
 3   Email                                                                           29 non-null     str
 4   Name                                                                            0 non-null      float64
 5   Last modified time                                                              0 non-null      float64
 6   What is your cohort number?                                                     29 non-null     str
 7   What month did your cohort start?                                               29 non-null     str
 8   What year is it?                                                                29 non-null     int64
 9   What is your age?                                                               29 non-null     int64
 10  What is your gender?                                                            29 non-null     str
 11  What's you dominant hand?                                                       29 non-null     str
 12  Do you prefer sweet or salty snacks?                                            29 non-null     str
 13  How many siblings do you have?                                                  29 non-null     int64
 14  What state do you live in?                                                      29 non-null     str
 15  What time zone are you in?                                                      29 non-null     str
 16  What language do you speak most often at home?                                  29 non-null     str
 17  What other languages can you speak or understand?                               25 non-null     str
 18  What month were you born?                                                       29 non-null     str
 19  Do you prefer calling or texting?                                               29 non-null     str
 20  What season do you enjoy the most?                                              29 non-null     str
 21  What best describes you?                                                        29 non-null     str
 22  How many people live in your household (including you?                          29 non-null     str
 23  How many pets do you have?                                                      28 non-null     str
 24  How many hours of sleep do you usually get each night?                          29 non-null     str
 25  Which best describes you right now?                                             29 non-null     str
 26  What industry do you currently work in (or most recently worked in)?
           29 non-null     str
 27  How many years have you worked?                                                 29 non-null     str
 28  How many hours each week do you plan to study for this course?                  29 non-null     str
 29  Have you ever taken an online course before?                                    29 non-null     str
 30  What OS are you using?                                                          29 non-null     str
 31  Which browser do you use the most?                                              29 non-null     str
 32  How comfortable are you learning new technology?                                29 non-null     int64
 33  About how many hours per day do you spend using a computer?                     29 non-null     str
 34  About how many hours a day do you spend on your phone?                          29 non-null     str
 35  What AI tools have you used?                                                    29 non-null     str
 36  Have you ever written computer code before (python, sql, c, JS, Java, ect...)?  29 non-null     str
 37  Which social media platforms do you use regularly?                              29 non-null     str
 38  What hobbies do you enjoy?                                                      29 non-null     str
 39  How often do you exercise?                                                      29 non-null     str
 40  Do you enjoy cooking?                                                           28 non-null     str
 41  Coffee, tea, both, neither?                                                     28 non-null     str
 42  Approximately how many books did you read last year?                            28 non-null     str
 43  Which music genres do you enjoy?                                                28 non-null     str
 44  Which movie or TV genres do you enjoy?                                          29 non-null     str
 45  What streaming services do you subscribe to?                                    27 non-null     str
 46  Are you a dog person, cat person, both, or neither?                             29 non-null     str
 47  Does pineapple belong on pizza?                                                 28 non-null     float64
 48  What is your favorite color?                                                    29 non-null     str
 49  What destination would you choose?                                              29 non-null     str
 50  Favorite board / card game?                                                     27 non-null     str
 51  Favorite video game?                                                            24 non-null     str
 52  Favorite movie?                                                                 28 non-null     str
 53  Favorite TV show?                                                               25 non-null     str
 54  What is your favorite sport to watch or play?                                   28 non-null     str
dtypes: float64(3), int64(5), str(47)
memory usage: 12.6 KB

In [14]:
df.isnull().sum()

ID                                                                                 0
Start time                                                                         0
Completion time                                                                    0
Email                                                                              0
Name                                                                              29
Last modified time                                                                29
What is your cohort number?                                                        0
What month did your cohort start?                                                  0
What year is it?                                                                   0
What is your age?                                                                  0
What is your gender?                                                               0
What's you dominant hand?                                                          0
Do you prefer sweet or salty snacks?                                               0
How many siblings do you have?                                                     0
What state do you live in?                                                         0
What time zone are you in?                                                         0
What language do you speak most often at home?                                     0
What other languages can you speak or understand?                                  4
What month were you born?                                                          0
Do you prefer calling or texting?                                                  0
What season do you enjoy the most?                                                 0
What best describes you?                                                           0
How many people live in your household (including you?                             0
How many pets do you have?                                                         1
How many hours of sleep do you usually get each night?                             0
Which best describes you right now?                                                0
What industry do you currently work in (or most recently worked in)?\n             0
How many years have you worked?                                                    0
How many hours each week do you plan to study for this course?                     0
Have you ever taken an online course before?                                       0
What OS are you using?                                                             0
Which browser do you use the most?                                                 0
How comfortable are you learning new technology?                                   0
About how many hours per day do you spend using a computer?                        0
About how many hours a day do you spend on your phone?                             0
What AI tools have you used?                                                       0
Have you ever written computer code before (python, sql, c, JS, Java, ect...)?     0
Which social media platforms do you use regularly?                                 0
What hobbies do you enjoy?                                                         0
How often do you exercise?                                                         0
Do you enjoy cooking?                                                              1
Coffee, tea, both, neither?                                                        1
Approximately how many books did you read last year?                               1
Which music genres do you enjoy?                                                   1
Which movie or TV genres do you enjoy?                                             0
What streaming services do you subscribe to?                                       2
Are you a dog person, cat person, both, or neither?                                0
Does pineapple belong on pizza?                                                    1
What is your favorite color?                                                       0
What destination would you choose?                                                 0
Favorite board / card game?                                                        2
Favorite video game?                                                               5
Favorite movie?                                                                    1
Favorite TV show?                                                                  4
What is your favorite sport to watch or play?                                      1
dtype: int64

In [16]:
qual_cols = df.select_dtypes(
    include=['object','string','category','bool']
)
print(qual_cols)

         Start time  Completion time      Email What is your cohort number?  \
0   8/4/26 11:47:47  8/4/26 11:53:02  anonymous                 2026-RTT-36
1   8/4/26 11:48:01  8/4/26 11:53:11  anonymous                 2026 RTT-36
2   8/4/26 11:47:53  8/4/26 11:53:12  anonymous                          36
3   8/4/26 11:48:01  8/4/26 11:54:22  anonymous                 2026-rtt-36
4   8/4/26 11:48:32  8/4/26 11:54:34  anonymous                 2026-RTT-36
5   8/4/26 11:47:42  8/4/26 11:54:51  anonymous              2026 - RTT -36
6   8/4/26 11:48:14  8/4/26 11:55:29  anonymous                          36
7   8/4/26 11:48:06  8/4/26 11:55:42  anonymous                 2026-RTT-36
8   8/4/26 11:48:08  8/4/26 11:55:59  anonymous                          36
9   8/4/26 11:47:49  8/4/26 11:56:16  anonymous                      RTT-36
10  8/4/26 11:48:47  8/4/26 11:56:51  anonymous                 2026-RTT-36
11  8/4/26 11:48:01  8/4/26 11:57:12  anonymous                  2026-RT-36
12  8/4/26 11:47:51  8/4/26 11:58:21  anonymous                 2026-RTT-36
13  8/4/26 11:47:42  8/4/26 11:58:51  anonymous                 2026-RTT-36
14  8/4/26 11:47:44  8/4/26 12:00:34  anonymous                 2026-rtt-36
15  8/4/26 11:47:46  8/4/26 12:00:39  anonymous                 2026-rtt-36
16  8/4/26 11:47:54  8/4/26 12:00:59  anonymous                          36
17  8/4/26 11:47:47  8/4/26 12:01:40  anonymous                 2026-RTT-36
18  8/4/26 11:48:16  8/4/26 12:01:51  anonymous                 2026-RTT-36
19  8/4/26 11:48:06  8/4/26 12:02:43  anonymous                 2026-rrt-36
20  8/4/26 11:47:42  8/4/26 12:03:37  anonymous                     2026-36
21  8/4/26 11:47:45  8/4/26 12:03:49  anonymous                 2026-rtt-36
22  8/4/26 11:47:44  8/4/26 12:04:15  anonymous                 2026-rtt-36
23  8/4/26 11:47:44  8/4/26 12:05:03  anonymous                 2026-RTT-36
24  8/4/26 11:47:52  8/4/26 12:17:23  anonymous                  2026-RT-36
25  8/4/26 11:48:02  8/4/26 12:38:12  anonymous                 2026-RTT-36
26  8/4/26 11:47:50  8/4/26 12:50:19  anonymous                 2026-rtt-36
27  8/4/26 12:58:33  8/4/26 13:01:35  anonymous                      RTT-36
28  8/4/26 13:07:43  8/4/26 13:14:10  anonymous                 2026-RTT-36

   What month did your cohort start? What is your gender?  \
0                             August                 Male
1                             August               Female
2                             August               Female
3                             August                 Male
4                             August                 Male
5                             August               Female
6                             August                 Male
7                             August               Female
8                             August               Female
9                             August                 Male
10                            August               Female
11                            August                 Male
12                            August               Female
13                            August                 Male
14                            August               Female
15                            August                 Male
16                            August               Female
17                            August               Female
18                            August                 Male
19                            August                 Male
20                            August               Female
21                            August                 Male
22                            August               Female
23                            August                 Male
24                            August                 Male
25                            August               Female
26                            August               Female
27                            August                 Male
28                            August               Female

   What's you dominant hand? Do you prefer sweet or salty snacks?  \
0                      Right                                Sweet
1                      Right                                Sweet
2                      Right                                Sweet
3                      Right                                Salty
4                      Right                                Salty
5                      Right                                Salty
6                      Right                                Salty
7                      Right                                Sweet
8                      Right                                Sweet
9                       Left                                Sweet
10                     Right                                Sweet
11                     Right                                Salty
12                      Left                                Salty
13             Ambidexterous                                Sweet
14                     Right                                Salty
15             Ambidexterous                                Salty
16                     Right                                Sweet
17                     Right                                Salty
18                     Right                                Sweet
19                     Right                                Salty
20                     Right                                Sweet
21                     Right                                Sweet
22                     Right                                Salty
23                     Right                                Sweet
24                     Right                                Sweet
25                     Right                                Sweet
26                     Right                                Salty
27                     Right                                Sweet
28                     Right                                Sweet

   What state do you live in? What time zone are you in?  ...  \
0                          OH                    Eastern  ...
1                        Ohio                    Eastern  ...
2                    Michigan                    Eastern  ...
3                    michigan                    Eastern  ...
4                    Missouri                    Central  ...
5                    Michigan                    Eastern  ...
6                    Michigan                    Eastern  ...
7                   Michighan                    Eastern  ...
8                        Ohio                    Eastern  ...
9                    Missouri                    Central  ...
10                       Ohio                    Eastern  ...
11                   Missouri                    Central  ...
12                   Missouri                    Central  ...
13                   Michigan                    Eastern  ...
14                   Michigan                    Eastern  ...
15                   Missouri                    Central  ...
16                       Ohio                    Eastern  ...
17                       Ohio                    Eastern  ...
18                   Missouri                    Central  ...
19                       Ohio                    Eastern  ...
20                       Ohio                    Eastern  ...
21                         MO                    Central  ...
22                       ohio                    Eastern  ...
23                         MO                    Central  ...
24                   Missouri                    Central  ...
25                   Michigan                    Eastern  ...
26                         OH                    Eastern  ...
27                   Michigan                    Eastern  ...
28                       Ohio                    Eastern  ...

               Which movie or TV genres do you enjoy?  \
0                                          Adventure;
1                             Reality;Action, comedy;
2                                        Anime;Drama;
3                             Thriller;Fantasy;scifi;
4                             Thriller;Reality;Drama;
5                                        Documentary;
6   Thriller;Horror;Drama;Fantasy;Reality;Document...
7                                        Documentary;
8                 Fantasy;Thriller;Drama;Documentary;
9                    Drama;Fantasy;Action and SCI-FI;
10                Thriller;Drama;Reality;Documentary;
11                Thriller;Drama;Fantasy;Documentary;
12                           Thriller;Horror;Fantasy;
13  Crime;Drama;Thriller;Anime;Fantasy;Reality;Doc...
14                                             Anime;
15  Anime;Thriller;Horror;Fantasy;Reality;Document...
16                       Horror;Thriller;Documentary;
17                         Drama;Documentary;Reality;
18                               Documentary;Fantasy;
19                     Horror;Drama;Fantasy;Thriller;
20  Drama;Reality;Documentary;Fantasy;Thriller;Act...
21                                     Drama;Reality;
22                                             Drama;
23                Reality;Thriller;Drama;Documentary;
24  Anime;Thriller;Horror;Drama;Fantasy;Reality;Do...
25                    Fantasy;Drama;Thriller;Romance;
26        Anime;Thriller;Drama;Horror;Fantasy;Comedy;
27                                              None;
28                                   Romantic/Comedy;

         What streaming services do you subscribe to?  \
0                                    Netflix;Youtube;
1                               Netflix;Youtube;Hulu;
2                         Netflix;Hulu;HBO;Paramount;
3                                  Netflix;mobilvids;
4                                    Netflix;Youtube;
5                                                 NaN
6                                           Hulu;HBO;
7                                            Netflix;
8                    Netflix;Hulu;HBO;Peacock;Disney;
9                  Netflix;Paramount;Hulu;HBO;Prime ;
10                               Netflix;HBO;Peacock;
11                                      Netflix;Hulu;
12  Paramount;Peacock;HBO;Hulu;Netflix;Prime, Star...
13                                      Netflix;Hulu;
14                                           Netflix;
15                                   Netflix;Youtube;
16                                   Netflix;Youtube;
17                                           Netflix;
18                                 Peacock;Paramount;
19                              Netflix;Hulu;Youtube;
20                 Netflix;Hulu;Paramount;HBO;Disney;
21                Netflix;Hulu;foxOne, roku, prime, ;
22                              Netflix;Hulu;Peacock;
23                              Netflix;Hulu;Youtube;
24  None, I'm not subscribed to any of those strea...
25                                      Amazon Prime;
26                                     Netflix;Prime;
27                                              None;
28                                                NaN

   Are you a dog person, cat person, both, or neither?  \
0                                             Neither
1                                                Both
2                                                Both
3                                                Both
4                                                 Dog
5                                             Neither
6                                                Both
7                                             Neither
8                                                 Dog
9                                                 Dog
10                                               Both
11                                                Cat
12                                            Neither
13                                            Neither
14                                            Neither
15                                                Dog
16                                            Neither
17                                            Neither
18                                                Dog
19                                                Cat
20                                            Neither
21                                                Cat
22                                            Neither
23                                                Dog
24                                               Both
25                                               Both
26                                            Neither
27                                                Cat
28                                                Dog

   What is your favorite color? What destination would you choose?  \
0                         Green                          Mountains
1                         Green                      National Park
2                          Blue                          Mountains
3                         Green                        Countryside
4                         White                              Beach
5                        Yellow                              Beach
6                         Black                              Beach
7                         Green                        Countryside
8                         Green                          Mountains
9                         Brown                           Big City
10                       Purple                              Beach
11                          Red                              Beach
12                        Green                              Beach
13                        Black                              Beach
14                       Orange                              Beach
15                         Blue                              Beach
16                       Purple                          Mountains
17                        Green                          Mountains
18                        Green                           Big City
19                        Green                              Beach
20                        Black                      National Park
21                        Black                           Big City
22                        Green                              Beach
23                         Blue                              Beach
24                        Black                           Big City
25                       Orange                          Mountains
26                         Blue                      National Park
27                         Blue                          Mountains
28                        Green                              Beach

   Favorite board / card game?               Favorite video game?  \
0                     monopoly                                NaN
1                          uno                         Mario Kart
2                          Uno                            Pac Man
3                     monopoly                     Tempest Rising
4                          UNO                         God of war
5                          NaN                                NaN
6                     Monopoly               Skyrim elder scrolls
7                       puzzle                                 no
8             What Do You Meme                         Mario Kart
9                     Monopoly                      Call of Duty
10                         uno                              mario
11                   monopoly                      Assassin Creed
12                       Taboo                      Mortal Kombat
13                      Spades                                UFC
14                    Sequence                                 No
15                         UNO                      Mortal Kombat
16            chess, badminton                              Pub G
17                         UNO                                NaN
18                        Ludo                         God of War
19                         NaN                                NaN
20                         UNO                     Mario Brothers
21                       chess                               none
22           Uno and Solitaire                   Candy Crush Saga
23                   monopoly                                  2k
24                 Spades, UNO  Madden Football and Soul Caliber
25                   Solitaire                                NaN
26                         Non                                Non
27                    Monopoly                         COD mobile
28                       Sorry                     Bomberman Hero

                                Favorite movie?  \
0                                      avengers
1                                        Friday
2                                     The Shack
3                              Bicentennial man
4                                       Kantara
5                                           NaN
6                               Living Out Loud
7                                            no
8                                   The Pianist
9                                    Lion King
10                                     twilight
11                                   Casablanca
12                                 Last Samurai
13                               You Got Served
14                              Indian/Bahubali
15                                       Matrix
16                     The pursuit of happiness
17                                       Avatar
18                                 White Chicks
19                                      Titanic
20                                     Malcom X
21                                     not sure
22  The Notebook , Inception , and White Chicks
23                               black panther
24          Stomp The yard, You Got Served, Saw
25                                Fifth-Element
26                                 Empire Waist
27                                   Scooby Doo
28                           A Walk to Remember

                                    Favorite TV show?  \
0                                        Harry potter
1                                            Blackish
2                           Avatar the Last Airbender
3                                       super natural
4                                       Young Sheldon
5                                                 NaN
6                                    Sex and the city
7                                                  no
8                                       Schitts Creek
9                                           Spongebob
10                                           not sure
11                                       Jack Richard
12                                    Game of Thrones
13                                    Bernie Mac Show
14                                                NaN
15                                       Walking Dead
16                                               none
17                                      gilmore girls
18                                               Loki
19                            I mostly watch YouTube.
20                                             Martin
21                                                NaN
22                             Scandal and This is us
23                                           billions
24  America's Best Dance Crew, So You Think You Ca...
25                                            Reacher
26                               Arrested Development
27                                       Henry Danger
28                                                NaN

   What is your favorite sport to watch or play?
0                                      badminton
1                                     Basketball

In [17]:
print(f'Duplicate records: {df.duplicated().sum()}')

Duplicate records: 0

In [20]:
number_cols=df.select_dtypes(
    include=['number']
).columns.tolist()
print(number_cols)

['ID', 'Name', 'Last modified time', 'What year is it?', 'What is your age?', 'How many siblings do you have?', 'How comfortable are you learning new technology?', 'Does pineapple belong on pizza?']