# R_GLAB 386.3.14 - Handling Missing Values

In [1]:
import pandas as pd
import numpy as np

In [ ]:
# Initializing the nested list with Data set
emp_list = [
    ['James', 36, 75, 5428000],
    ['Villers', 38, 74, 3428000],
    ['VKole', 31, 70, 8428000],
    ['Smith', 34, 80, 4428000],
    ['Gayle', 40, 100, 4528000],
    ['Adam', 40, np.nan, 4528000],
    ['Rooter', 33, 72, 7028000],
    ['Peterson', 42, 85, 2528000],
    ['lynda', 42, 85, np.nan],
    [np.nan, 42, 85, np.nan],
    ['John', 41, 85, 1528000]
    ]

In [3]:
headers = ['Name', 'Age', 'Weigh (kg)', 'Salary']

df = pd.DataFrame(emp_list, columns=headers)

### Initial Data Integrity CheckList
1.  Look at shape (rows, cols) - lets you know how many variables you are working with and how large the dataset it
2.  Look at the top 5 and bottom 5 records (.head(), tail())
3.  Look at the data types (.info(), .dtypes)
4.  Look at desctiptive statistics (.describe()) - making sure every falls in normal range, taking note if not.
5.  Look at values counts of categorical variables (.value_counts), (unique())
6.  Take note of null/missing values (df.isnull().sum())
7.  Examine for duplicate records (df.duplicated().sum())

In [5]:
# Destructure the shape tuple and print
rows, cols = df.shape

print(f'Rows: {rows}')
print(f'Cols: {cols}')

Rows: 11
Cols: 4

In [7]:
print('Head: \n', df.head())

Head:
       Name  Age  Weigh (kg)     Salary
0    James   36        75.0  5428000.0
1  Villers   38        74.0  3428000.0
2    VKole   31        70.0  8428000.0
3    Smith   34        80.0  4428000.0
4    Gayle   40       100.0  4528000.0

In [8]:
print('Tail: \n', df.tail())

Tail:
         Name  Age  Weigh (kg)     Salary
6     Rooter   33        72.0  7028000.0
7   Peterson   42        85.0  2528000.0
8      lynda   42        85.0        NaN
9        NaN   42        85.0        NaN
10      John   41        85.0  1528000.0

In [13]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        10 non-null     str
 1   Age         11 non-null     int64
 2   Weigh (kg)  10 non-null     float64
 3   Salary      9 non-null      float64
dtypes: float64(2), int64(1), str(1)
memory usage: 484.0 bytes
None

In [15]:
print(df.describe())

             Age  Weigh (kg)        Salary
count  11.000000   10.000000  9.000000e+00
mean   38.090909   81.100000  4.650222e+06
std     3.986340    8.900062  2.131770e+06
min    31.000000   70.000000  1.528000e+06
25%    35.000000   74.250000  3.428000e+06
50%    40.000000   82.500000  4.528000e+06
75%    41.500000   85.000000  5.428000e+06
max    42.000000  100.000000  8.428000e+06

In [17]:
print(f'Duplicate Records: {df.duplicated().sum()}')

Duplicate Records: 0

In [20]:
print('-'*10, 'Missing Values', '-'*10)
print(df.isna().sum())

---------- Missing Values ----------
Name          1
Age           0
Weigh (kg)    1
Salary        2
dtype: int64

In [ ]:
print('-'*10, 'Before Handling Missing Values', '-'*10)
print(df)

---------- Before Handling Missing Values ----------
        Name  Age  Weigh (kg)     Salary
0      James   36        75.0  5428000.0
1    Villers   38        74.0  3428000.0
2      VKole   31        70.0  8428000.0
3      Smith   34        80.0  4428000.0
4      Gayle   40       100.0  4528000.0
5       Adam   40         NaN  4528000.0
6     Rooter   33        72.0  7028000.0
7   Peterson   42        85.0  2528000.0
8      lynda   42        85.0        NaN
9        NaN   42        85.0        NaN
10      John   41        85.0  1528000.0

### What to do when you find missing data?
-   Take note of what columns are missing data
-   Why is it missing? (not always possible, but you should take a look anyway)
-   Decided what to do with missing data:
    -   Drop missing records (`df.dropna()`) - not reccommended you might lose value data
    -   Impute (replace) missing values with a placeholder 'NA', 'Pending'
    -   If ordered data forward or back fill day
    -   Categorical:  Impute with the mode.
    -   Quantitative Data: Impute with mean (normal distribution) or median (skewed/non-normal distribution)

In [23]:
df = df.fillna('None')

In [27]:
print('-'*10, 'After Handling Missing Values', '-'*10)
print(df)

---------- After Handling Missing Values ----------
        Name  Age Weigh (kg)     Salary
0      James   36       75.0  5428000.0
1    Villers   38       74.0  3428000.0
2      VKole   31       70.0  8428000.0
3      Smith   34       80.0  4428000.0
4      Gayle   40      100.0  4528000.0
5       Adam   40       None  4528000.0
6     Rooter   33       72.0  7028000.0
7   Peterson   42       85.0  2528000.0
8      lynda   42       85.0       None
9       None   42       85.0       None
10      John   41       85.0  1528000.0

In [26]:
print(df.describe())

             Age
count  11.000000
mean   38.090909
std     3.986340
min    31.000000
25%    35.000000
50%    40.000000
75%    41.500000
max    42.000000

### Imputing Individual Columns

In [35]:
headers = ['Name', 'Age', 'Weight (kg)', 'Salary']

df = pd.DataFrame(emp_list, columns=headers)

In [36]:
print('-'*10, 'Before Handling Missing Values', '-'*10)
print(df)

---------- Before Handling Missing Values ----------
        Name  Age  Weight (kg)     Salary
0      James   36         75.0  5428000.0
1    Villers   38         74.0  3428000.0
2      VKole   31         70.0  8428000.0
3      Smith   34         80.0  4428000.0
4      Gayle   40        100.0  4528000.0
5       Adam   40          NaN  4528000.0
6     Rooter   33         72.0  7028000.0
7   Peterson   42         85.0  2528000.0
8      lynda   42         85.0        NaN
9        NaN   42         85.0        NaN
10      John   41         85.0  1528000.0

In [41]:
median_weight = df['Weight (kg)'].median()

df['Weight (kg)'] = df['Weight (kg)'].fillna(median_weight)

# Impute salary with an appropriate value
mean_salary = df['Salary'].mean()
df['Salary'] = df['Salary'].fillna(mean_salary)

In [42]:
print('-'*10, 'After Handling Missing Values', '-'*10)
print(df)

---------- After Handling Missing Values ----------
        Name  Age  Weight (kg)        Salary
0      James   36         75.0  5.428000e+06
1    Villers   38         74.0  3.428000e+06
2      VKole   31         70.0  8.428000e+06
3      Smith   34         80.0  4.428000e+06
4      Gayle   40        100.0  4.528000e+06
5       Adam   40         82.5  4.528000e+06
6     Rooter   33         72.0  7.028000e+06
7   Peterson   42         85.0  2.528000e+06
8      lynda   42         85.0  4.650222e+06
9        NaN   42         85.0  4.650222e+06
10      John   41         85.0  1.528000e+06

In [45]:
headers = ['Name', 'Age', 'Weight (kg)', 'Salary']

df = pd.DataFrame(emp_list, columns=headers)

print('-'*10, 'Before Handling Missing Values', '-'*10)
print(df)

---------- Before Handling Missing Values ----------
        Name  Age  Weight (kg)     Salary
0      James   36         75.0  5428000.0
1    Villers   38         74.0  3428000.0
2      VKole   31         70.0  8428000.0
3      Smith   34         80.0  4428000.0
4      Gayle   40        100.0  4528000.0
5       Adam   40          NaN  4528000.0
6     Rooter   33         72.0  7028000.0
7   Peterson   42         85.0  2528000.0
8      lynda   42         85.0        NaN
9        NaN   42         85.0        NaN
10      John   41         85.0  1528000.0

In [46]:
subset = df[['Weight (kg)', 'Salary']].fillna('Pending')
print(subset)

   Weight (kg)     Salary
0         75.0  5428000.0
1         74.0  3428000.0
2         70.0  8428000.0
3         80.0  4428000.0
4        100.0  4528000.0
5      Pending  4528000.0
6         72.0  7028000.0
7         85.0  2528000.0
8         85.0    Pending
9         85.0    Pending
10        85.0  1528000.0

In [49]:
mean_salary = df['Salary'].mean()
median_weight = df['Weight (kg)'].median()

df2 = df.fillna(value={'Name': 'Unknown', 'Salary': mean_salary, 'Weight (kg)': median_weight})

print(df2)

        Name  Age  Weight (kg)        Salary
0      James   36         75.0  5.428000e+06
1    Villers   38         74.0  3.428000e+06
2      VKole   31         70.0  8.428000e+06
3      Smith   34         80.0  4.428000e+06
4      Gayle   40        100.0  4.528000e+06
5       Adam   40         82.5  4.528000e+06
6     Rooter   33         72.0  7.028000e+06
7   Peterson   42         85.0  2.528000e+06
8      lynda   42         85.0  4.650222e+06
9    Unknown   42         85.0  4.650222e+06
10      John   41         85.0  1.528000e+06

In [50]:
technologies = {
    'Courses':["Spark",np.nan,"Hadoop","Python","pandas",np.nan,"Java"],
    'Fee' :[20000,25000, np.nan,22000,24000,np.nan,22000],
    'Duration':[np.nan,'40days','35days', np.nan,'60days','50days','55days'],
    'Discount':[1000,np.nan,1500,np.nan,2500,2100,np.nan]
              }
df = pd.DataFrame(technologies)
print(df)

  Courses      Fee Duration  Discount
0   Spark  20000.0      NaN    1000.0
1     NaN  25000.0   40days       NaN
2  Hadoop      NaN   35days    1500.0
3  Python  22000.0      NaN       NaN
4  pandas  24000.0   60days    2500.0
5     NaN      NaN   50days    2100.0
6    Java  22000.0   55days       NaN

In [ ]:
df2 = df.replace(np.nan, '')
df2

  Courses      Fee Duration Discount
0   Spark  20000.0            1000.0
1          25000.0   40days
2  Hadoop            35days   1500.0
3  Python  22000.0
4  pandas  24000.0   60days   2500.0
5                    50days   2100.0
6    Java  22000.0   55days

In [53]:
df2 = df[['Courses', 'Fee']] = df[['Courses', 'Fee']].fillna('Pending')

df2

   Courses      Fee
0    Spark  20000.0
1  Pending  25000.0
2   Hadoop  Pending
3   Python  22000.0
4   pandas  24000.0
5  Pending  Pending
6     Java  22000.0